import {
  createFlow,
  type PracticeStage,
  type PracticeStory,
} from "../../shared/story.ts";
import type { ArtPackId } from "./art-packs.ts";

const AUDIO_ROOT = "/audio/office-gig";

export const OFFICE_GIG_STAGES: PracticeStage[] = [
  {
    id: "gig-notice",
    number: 1,
    title: "Noticing",
    jpTitle: "気づく",
    sceneId: "lounge",
    castId: "coworker",
    transition: {
      id: "gig-notice-open",
      japanese: "金曜日の昼休み。休憩室で、同僚が音楽を聞いていた。",
      reading:
        "きんようびのひるやすみ。きゅうけいしつで、どうりょうがおんがくをきいていた。",
      translation:
        "Friday lunch break. In the lounge, a coworker was listening to music.",
      audioSrc: `${AUDIO_ROOT}/gig-notice-open.mp3`,
    },
    bubbles: [
      {
        id: "gig-notice-hello",
        speaker: "other",
        mode: "autoplay",
        japanese: "あ、おつかれさまです。",
        reading: "あ、おつかれさまです。",
        translation: "Oh — hi.",
        audioSrc: `${AUDIO_ROOT}/gig-notice-hello.mp3`,
      },
      {
        id: "gig-notice-hello-back",
        speaker: "learner",
        mode: "autoplay",
        japanese: "おつかれさまです。",
        reading: "おつかれさまです。",
        translation: "Hi.",
        audioSrc: `${AUDIO_ROOT}/gig-notice-hello-back.mp3`,
      },
      {
        id: "gig-notice-shirt",
        speaker: "learner",
        mode: "speak",
        japanese: "そのTシャツ、何のバンドですか。",
        reading: "そのてぃーしゃつ、なんのばんどですか。",
        translation: "That T-shirt — what band is it?",
        audioSrc: `${AUDIO_ROOT}/gig-notice-shirt.mp3`,
        accepted: [
          "それ、何のバンドですか",
          "Tシャツ、何のバンドですか",
          "何のバンドですか",
          "そのTシャツ、何のバンドのですか",
        ],
      },
      {
        id: "gig-notice-highschool",
        speaker: "other",
        mode: "autoplay",
        japanese: "高校のときからずっと好きなバンドなんですよ。",
        reading: "こうこうのときからずっとすきなばんどなんですよ。",
        translation: "It's a band I've loved since high school.",
        audioSrc: `${AUDIO_ROOT}/gig-notice-highschool.mp3`,
      },
      {
        id: "gig-notice-rock",
        speaker: "learner",
        mode: "speak",
        japanese: "私もロック、好きなんです。",
        reading: "わたしもろっく、すきなんです。",
        translation: "I'm into rock too, actually.",
        audioSrc: `${AUDIO_ROOT}/gig-notice-rock.mp3`,
        accepted: [
          "私もロックが好きです",
          "私もロックが好きなんです",
          "ロック、好きなんです",
          "私もロック好きです",
        ],
      },
      {
        id: "gig-notice-guitar",
        speaker: "other",
        mode: "autoplay",
        japanese: "じつは私、ギターをやってるんですよ。",
        reading: "じつはわたし、ぎたーをやってるんですよ。",
        translation: "Actually, I play guitar myself.",
        audioSrc: `${AUDIO_ROOT}/gig-notice-guitar.mp3`,
      },
    ],
  },
  {
    id: "gig-taste",
    number: 2,
    title: "Taste",
    jpTitle: "好み",
    sceneId: "lounge-close",
    castId: "coworker",
    transition: {
      id: "gig-taste-open",
      japanese: "自動販売機の前に、缶コーヒーが二つ並んだ。",
      reading:
        "じどうはんばいきのまえに、かんこーひーがふたつならんだ。",
      translation: "Two cans of coffee stood beside the vending machine.",
      audioSrc: `${AUDIO_ROOT}/gig-taste-open.mp3`,
    },
    bubbles: [
      {
        id: "gig-taste-ask",
        speaker: "other",
        mode: "autoplay",
        japanese: "ふだんはどんなの聞くんですか。",
        reading: "ふだんはどんなのきくんですか。",
        translation: "What do you usually listen to?",
        audioSrc: `${AUDIO_ROOT}/gig-taste-ask.mp3`,
      },
      {
        id: "gig-taste-why",
        speaker: "learner",
        mode: "speak",
        japanese: "ギターの音が好きで、よくロックを聞きます。",
        reading: "ぎたーのおとがすきで、よくろっくをききます。",
        translation:
          "I love the sound of a guitar, so I listen to a lot of rock.",
        audioSrc: `${AUDIO_ROOT}/gig-taste-why.mp3`,
        accepted: [
          "ギターの音が好きなので、よくロックを聞きます",
          "ギターの音が好きで、ロックをよく聞きます",
          "ギターの音が好きで、よくロックを聞いています",
          "ギターの音が好きなので、ロックをよく聞きます",
        ],
      },
      {
        id: "gig-taste-agree",
        speaker: "other",
        mode: "autoplay",
        japanese: "ギターがいいと、それだけで聞いちゃいますよね。",
        reading: "ぎたーがいいと、それだけできいちゃいますよね。",
        translation:
          "When the guitar's good, that alone gets you listening, right?",
        audioSrc: `${AUDIO_ROOT}/gig-taste-agree.mp3`,
      },
      {
        id: "gig-taste-recommend",
        speaker: "learner",
        mode: "speak",
        japanese: "じゃあ、おすすめはなんですか。",
        reading: "じゃあ、おすすめはなんですか。",
        translation: "So what would you recommend?",
        audioSrc: `${AUDIO_ROOT}/gig-taste-recommend.mp3`,
        accepted: [
          "おすすめはなんですか",
          "じゃあ、おすすめを教えてください",
          "おすすめのバンドはなんですか",
        ],
      },
      {
        id: "gig-taste-saturday",
        speaker: "other",
        mode: "autoplay",
        japanese: "ちょうど土曜日にライブがあるんですよ。",
        reading: "ちょうどどようびにらいぶがあるんですよ。",
        translation: "There's actually a gig this Saturday.",
        audioSrc: `${AUDIO_ROOT}/gig-taste-saturday.mp3`,
      },
      {
        id: "gig-taste-venue",
        speaker: "other",
        mode: "autoplay",
        japanese: "小さいライブハウスなんですけど、音がいいんですよ。",
        reading:
          "ちいさいらいぶはうすなんですけど、おとがいいんですよ。",
        translation: "It's a small live house, but the sound's great.",
        audioSrc: `${AUDIO_ROOT}/gig-taste-venue.mp3`,
      },
    ],
  },
  {
    id: "gig-join",
    number: 3,
    title: "Joining",
    jpTitle: "行きたい",
    sceneId: "entrance",
    castId: "coworker",
    transition: {
      id: "gig-join-open",
      japanese: "夕方、会社の玄関でまた会った。",
      reading: "ゆうがた、かいしゃのげんかんでまたあった。",
      translation: "That evening, you met again at the office entrance.",
      audioSrc: `${AUDIO_ROOT}/gig-join-open.mp3`,
    },
    bubbles: [
      {
        id: "gig-join-earlier",
        speaker: "other",
        mode: "autoplay",
        japanese: "あ、さっきの話なんですけど。",
        reading: "あ、さっきのはなしなんですけど。",
        translation: "Oh — about what I was saying earlier.",
        audioSrc: `${AUDIO_ROOT}/gig-join-earlier.mp3`,
      },
      {
        id: "gig-join-spare",
        speaker: "other",
        mode: "autoplay",
        japanese: "じつは、チケットが一枚あまってるんです。",
        reading: "じつは、ちけっとがいちまいあまってるんです。",
        translation: "I've actually got a spare ticket.",
        audioSrc: `${AUDIO_ROOT}/gig-join-spare.mp3`,
      },
      {
        id: "gig-join-come",
        speaker: "learner",
        mode: "speak",
        japanese: "私も行ってもいいですか。",
        reading: "わたしもいってもいいですか。",
        translation: "Could I come along too?",
        audioSrc: `${AUDIO_ROOT}/gig-join-come.mp3`,
        accepted: [
          "行ってもいいですか",
          "私も行っていいですか",
          "一緒に行ってもいいですか",
          "私も行きたいです",
        ],
      },
      {
        id: "gig-join-together",
        speaker: "other",
        mode: "autoplay",
        japanese: "ぜひ、一緒に行きましょう。",
        reading: "ぜひ、いっしょにいきましょう。",
        translation: "Please do — let's go together.",
        audioSrc: `${AUDIO_ROOT}/gig-join-together.mp3`,
      },
      {
        id: "gig-join-price",
        speaker: "learner",
        mode: "speak",
        japanese: "チケットはいくらですか。",
        reading: "ちけっとはいくらですか。",
        translation: "How much is the ticket?",
        audioSrc: `${AUDIO_ROOT}/gig-join-price.mp3`,
        accepted: [
          "いくらですか",
          "チケット、いくらですか",
          "チケットはおいくらですか",
        ],
      },
      {
        id: "gig-join-cash",
        speaker: "other",
        mode: "autoplay",
        japanese: "三千円ですけど、当日でいいですよ。",
        reading: "さんぜんえんですけど、とうじつでいいですよ。",
        translation: "Three thousand yen — you can pay on the day, though.",
        audioSrc: `${AUDIO_ROOT}/gig-join-cash.mp3`,
      },
    ],
  },
  {
    id: "gig-meet",
    number: 4,
    title: "Meeting up",
    jpTitle: "待ち合わせ",
    sceneId: "entrance-close",
    castId: "coworker",
    transition: {
      id: "gig-meet-open",
      japanese: "外は、もう暗くなっていた。",
      reading: "そとは、もうくらくなっていた。",
      translation: "Outside, it had already grown dark.",
      audioSrc: `${AUDIO_ROOT}/gig-meet-open.mp3`,
    },
    bubbles: [
      {
        id: "gig-meet-six",
        speaker: "other",
        mode: "autoplay",
        japanese: "土曜日、六時でいいですか。",
        reading: "どようび、ろくじでいいですか。",
        translation: "Saturday at six — does that work?",
        audioSrc: `${AUDIO_ROOT}/gig-meet-six.mp3`,
      },
      {
        id: "gig-meet-where",
        speaker: "learner",
        mode: "speak",
        japanese: "じゃあ、どこで待ち合わせしますか。",
        reading: "じゃあ、どこでまちあわせしますか。",
        translation: "Where should we meet, then?",
        audioSrc: `${AUDIO_ROOT}/gig-meet-where.mp3`,
        accepted: [
          "どこで待ち合わせしますか",
          "待ち合わせはどこですか",
          "じゃあ、どこで会いますか",
          "どこで待ち合わせますか",
        ],
      },
      {
        id: "gig-meet-east",
        speaker: "other",
        mode: "autoplay",
        japanese: "駅の東口はどうですか。",
        reading: "えきのひがしぐちはどうですか。",
        translation: "How about the east exit of the station?",
        audioSrc: `${AUDIO_ROOT}/gig-meet-east.mp3`,
      },
      {
        id: "gig-meet-forward",
        speaker: "learner",
        mode: "speak",
        japanese: "楽しみにしています。",
        reading: "たのしみにしています。",
        translation: "I'm looking forward to it.",
        audioSrc: `${AUDIO_ROOT}/gig-meet-forward.mp3`,
        accepted: ["楽しみです", "楽しみにしてます"],
      },
      {
        id: "gig-meet-bye",
        speaker: "other",
        mode: "autoplay",
        japanese: "では、また土曜日に。",
        reading: "では、またどようびに。",
        translation: "See you Saturday, then.",
        audioSrc: `${AUDIO_ROOT}/gig-meet-bye.mp3`,
      },
    ],
  },
];

const OFFICE_GIG_FLOW = createFlow(OFFICE_GIG_STAGES);

export const OFFICE_GIG_STORY = {
  id: "office-gig",
  artPackId: "office",
  title: {
    ja: "土曜日のライブ",
    en: "Saturday's gig",
  },
  stages: OFFICE_GIG_STAGES,
  flow: OFFICE_GIG_FLOW,
} satisfies PracticeStory<ArtPackId>;
